import Header from "@/component/organisms/Header";
import { SocketProvider } from "@/context/SocketContext";
import { CustomProvider } from "@/store/customProvider";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-modern-drawer/dist/index.css";
import "react-phone-input-2/lib/style.css";
import { ToastContainer } from "react-toastify";
import "./css/color.css";
import "./css/global.css";
import "./css/typography.css";

export const metadata = {
  title: "Shipping Partner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <CustomProvider>
          <SocketProvider>
            <Header />
            {children}
            {/* <Footer /> */}
          </SocketProvider>
        </CustomProvider>
      </body>
    </html>
  );
}
