export const merchantTableBody = [
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "In-Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "In-Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "In-Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
    {
        name: "John Doe",
        email: "john@yopmail.com",
        date: "Jun 30,2024",
        phone: "(316) 555-0116",
        shipment: "Manual",
        country: "Brazil",
        status: "Active",
        city: "La Plata",
    },
]

export const productRequestsTableBody = [
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
    },
]

export const merchantDetailTableBody = [
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        category: "Jewelery",
        date: "Jun 30,2024",
        cost: "$468.3",
        sale: "$468.3",
        wholesale: "5"
    },
]

export const merchantManualShipmentsTableBody = [
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Pending",
    },
    {
        name: "Aniwell Filtabac Antibacterial Cream",
        buyer: "Irving O'Keefe",
        date: "Jun 30,2024",
        price: "$468.3",
        status: "Delivered",
    },
    
]

export const giftTableBody = [
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "In-Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "In-Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "In-Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "In-Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "Active",
    },
    {
        title: "Gift Card",
        start: "Jun 30,2024",
        end: "Jun 30,2025",
        price: "$468.3",
        status: "In-Active",
    },
]

export const merchantsTableData = [
    {
      merchants: "Ali Traders",
      email: "ali@traders.com",
      date: "2025-02-14",
      shipping: "Standard",
    },
    {
      merchants: "Noor Mart",
      email: "support@noormart.sa",
      date: "2025-03-01",
      shipping: "Express",
    },
    {
      merchants: "GlobalTech",
      email: "contact@globaltech.com",
      date: "2025-01-20",
      shipping: "Standard",
    },
    {
      merchants: "Al Safa Electronics",
      email: "sales@alsafa.sa",
      date: "2025-04-05",
      shipping: "Same-day",
    },
    {
      merchants: "Fashion Hub",
      email: "hello@fashionhub.com",
      date: "2025-02-28",
      shipping: "Next-day",
    },
    {
      merchants: "Ali Traders",
      email: "ali@traders.com",
      date: "2025-02-14",
      shipping: "Standard",
    },
    // {
    //   merchants: "Noor Mart",
    //   email: "support@noormart.sa",
    //   date: "2025-03-01",
    //   shipping: "Express",
    // },
    // {
    //   merchants: "GlobalTech",
    //   email: "contact@globaltech.com",
    //   date: "2025-01-20",
    //   shipping: "Standard",
    // },
    // {
    //   merchants: "Al Safa Electronics",
    //   email: "sales@alsafa.sa",
    //   date: "2025-04-05",
    //   shipping: "Same-day",
    // },
    // {
    //   merchants: "Fashion Hub",
    //   email: "hello@fashionhub.com",
    //   date: "2025-02-28",
    //   shipping: "Next-day",
    // },
    // {
    //   merchants: "Ali Traders",
    //   email: "ali@traders.com",
    //   date: "2025-02-14",
    //   shipping: "Standard",
    // },
    // {
    //   merchants: "Noor Mart",
    //   email: "support@noormart.sa",
    //   date: "2025-03-01",
    //   shipping: "Express",
    // },
    // {
    //   merchants: "GlobalTech",
    //   email: "contact@globaltech.com",
    //   date: "2025-01-20",
    //   shipping: "Standard",
    // },
    // {
    //   merchants: "Al Safa Electronics",
    //   email: "sales@alsafa.sa",
    //   date: "2025-04-05",
    //   shipping: "Same-day",
    // },
    // {
    //   merchants: "Fashion Hub",
    //   email: "hello@fashionhub.com",
    //   date: "2025-02-28",
    //   shipping: "Next-day",
    // },
  ];
  
  
  export const disputeTableData = [
      {
        reason: "Product not delivered on time",
        Username: "ahmed_khan",
        category: "Logistics",
        Date: "2025-04-20",
        Status: "pending",
      },
      {
        reason: "Item received was damaged",
        Username: "sara.ali",
        category: "Product Quality",
        Date: "2025-04-18",
        Status: "resolved",
      },
      {
        reason: "Wrong item delivered",
        Username: "faisal92",
        category: "Order Issue",
        Date: "2025-04-15",
        Status: "rejected",
      },
      {
        reason: "Refund not processed",
        Username: "noor123",
        category: "Payment",
        Date: "2025-04-10",
        Status: "pending",
      },
      {
        reason: "Warranty not honored",
        Username: "mariam_m",
        category: "Support",
        Date: "2025-04-08",
        Status: "resolved",
      },
    ];
    
  
  
    export const categorTableData = [
      {
        categoryName: "Electronics",
        date: "2025-04-01",
        status: "active",
      },
      {
        categoryName: "Home Appliances",
        date: "2025-03-28",
        status: "deactivate",
      },
      {
        categoryName: "Fashion",
        date: "2025-04-15",
        status: "active",
      },
      {
        categoryName: "Books",
        date: "2025-04-10",
        status: "deactivate",
      },
      {
        categoryName: "Beauty & Health",
        date: "2025-04-05",
        status: "active",
      },
    ];

    export const giftDetailTableBody = [
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
        {
            username: "Jane Cooper",
            email: "georgia.young@example.com",
            usedBy: "Gift Card",
            start: "Jun 30,2024",
            end: "Jun 30,2025",
        },
    ]   
    

    export const billingHistoryTableData = [
        {
          username: "john_doe",
          userType: "Standard",
          date: "2025-04-15",
          amount: "$120.00",
          commission: "10%",
          discount: "5%",
          status: "completed",
        },
        {
          username: "sarah_smith",
          userType: "Premium",
          date: "2025-04-20",
          amount: "$250.00",
          commission: "15%",
          discount: "10%",
          status: "completed",
        },
        {
          username: "michael_brown",
          userType: "Enterprise",
          date: "2025-04-12",
          amount: "$980.00",
          commission: "20%",
          discount: "15%",
          status: "completed",
        },
        {
          username: "emma_white",
          userType: "Standard",
          date: "2025-04-25",
          amount: "$75.00",
          commission: "5%",
          discount: "2%",
          status: "pending",
        },
        {
          username: "liam_jones",
          userType: "Premium",
          date: "2025-04-28",
          amount: "$310.00",
          commission: "12%",
          discount: "8%",
          status: "completed",
        },
      ];
      

    export const withdrawRequestTableData = [
        {
          username: "john_doe",
          userType: "Standard",
          date: "2025-04-15",
          amount: "$120.00",
          commission: "10%",
          discount: "5%",
          status: "completed",
        },
        {
          username: "sarah_smith",
          userType: "Premium",
          date: "2025-04-20",
          amount: "$250.00",
          commission: "15%",
          discount: "10%",
          status: "completed",
        },
        {
          username: "michael_brown",
          userType: "Enterprise",
          date: "2025-04-12",
          amount: "$980.00",
          commission: "20%",
          discount: "15%",
          status: "completed",
        },
        {
          username: "emma_white",
          userType: "Standard",
          date: "2025-04-25",
          amount: "$75.00",
          commission: "5%",
          discount: "2%",
          status: "pending",
        },
        {
          username: "liam_jones",
          userType: "Premium",
          date: "2025-04-28",
          amount: "$310.00",
          commission: "12%",
          discount: "8%",
          status: "completed",
        },
      ];
      

      export const userTableBody = [
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "5",
            country: "Brazil",
            status: "In-Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "10",
            country: "Brazil",
            status: "In-Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "In-Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "10",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
        {
            name: "John Doe",
            email: "john@yopmail.com",
            date: "Jun 30,2024",
            phone: "(316) 555-0116",
            orders: "1",
            country: "Brazil",
            status: "Active",
            city: "La Plata",
        },
    ]      